<?php
/**
 * Registers the ACF options page that becomes available after selection.
 *
 * @package Landing_Page
 */

namespace Landing_Page\Admin;

/**
 * Adds an ACF options page under Pages when configured.
 */
class Acf_Options_Page {
	private const POST_ID = 'landing_page_options';

	/**
	 * Hook into ACF initialization.
	 */
	public function __construct() {
		\add_action( 'acf/init', [ $this, 'register_options_page' ] );
		\add_action( 'acf/init', [ $this, 'register_fields' ] );
	}

	/**
	 * Register the Landing Page options page when prerequisites are met.
	 */
	public function register_options_page(): void {
		if ( ! \function_exists( 'acf_add_options_sub_page' ) ) {
			return;
		}

		if ( 0 === (int) \get_option( Settings_Page::OPTION_NAME, 0 ) ) {
			return;
		}

		\acf_add_options_sub_page(
			[
				'page_title'      => \__( 'Landing Page', 'impeka-landing-page' ),
				'menu_title'      => \__( 'Landing Page', 'impeka-landing-page' ),
				'parent_slug'     => 'edit.php?post_type=page',
				'menu_slug'       => 'landing-page-acf-settings',
				'capability'      => 'edit_pages',
				'position'        => false,
				'redirect'        => false,
				'post_id'         => self::POST_ID,
				'update_button'   => \__( 'Save Landing Page Settings', 'impeka-landing-page' ),
				'updated_message' => \__( 'Landing Page settings saved.', 'impeka-landing-page' ),
			]
		);
	}

	/**
	 * Register the Landing Page's custom fields
	 */
	public function register_fields(): void {

		\acf_add_local_field_group(
			array(
				'key'    => 'group_6924bbbf96b8f',
				'title'  => \__( 'Landing Page Header', 'impeka-landing-page' ),
				'fields' => array(
					array(
						'key'               => 'field_6924bbc46f1f5',
						'label'             => \__( 'CCA Logo', 'impeka-landing-page' ),
						'name'              => 'cca_logo',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
					),
					array(
						'key' => 'field_6925c6c55498e',
						'label' => \__( 'Background Video', 'impeka-landing-page' ),
						'name' => 'background_video',
						'aria-label' => '',
						'type' => 'file',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'min_size' => '',
						'max_size' => '',
						'mime_types' => '',
						'allow_in_bindings' => 0,
					),
					array(
						'key'               => 'field_6924bc156f1f6',
						'label'             => \__( 'Move It Logo', 'impeka-landing-page' ),
						'name'              => 'move_it_logo',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
					),
					array(
						'key'               => 'field_6924bc336f1f7',
						'label'             => \__( 'Move It Tagline', 'impeka-landing-page' ),
						'name'              => 'move_it_tagline',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924bc436f1f8',
						'label'             => \__( 'Lead', 'impeka-landing-page' ),
						'name'              => 'lead',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 1,
					),
					array(
						'key'               => 'field_6924bc656f1f9',
						'label'             => \__( 'Header Button', 'impeka-landing-page' ),
						'name'              => 'header_button',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'allow_in_bindings' => 0,
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'landing-page-acf-settings',
						),
					),
				),
				'menu_order'            => 1,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		

		\acf_add_local_field_group(
			array(
				'key'    => 'group_6924c641a229a',
				'title'  => \__( 'Habits', 'impeka-landing-page' ),
				'fields' => array(
					array(
						'key'               => 'field_6924c642953b8',
						'label'             => \__( 'Title', 'impeka-landing-page' ),
						'name'              => 'title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key' => 'field_6924d8f04b26c',
						'label' => __( 'Image', 'impeka-landing-page' ),
						'name' => 'habits_image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => 'jpg,png',
						'allow_in_bindings' => 0,
						'preview_size' => 'medium',
					),
					array(
						'key'               => 'field_6924c65d953b9',
						'label'             => \__( 'Habits List', 'impeka-landing-page' ),
						'name'              => 'habits_list',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => \__( 'Add Row', 'impeka-landing-page' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6924c666953ba',
								'label'             => \__( 'Habit', 'impeka-landing-page' ),
								'name'              => 'habit',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6924c65d953b9',
							),
							array(
								'key' => 'field_6925c6731830e',
								'label' => \__( 'Description', 'impeka-landing-page' ),
								'name' => 'description',
								'aria-label' => '',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'allow_in_bindings' => 0,
								'rows' => '',
								'placeholder' => '',
								'new_lines' => '',
								'parent_repeater' => 'field_6924c65d953b9',
							),
						),
					),
					array(
						'key'               => 'field_6924c67b953bb',
						'label'             => \__( 'Habits Footnote', 'impeka-landing-page' ),
						'name'              => 'habits_footnote',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 1,
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'landing-page-acf-settings',
						),
					),
				),
				'menu_order'            => 10,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		\acf_add_local_field_group(
			array(
				'key'    => 'group_6924c6a134bbe',
				'title'  => \__( 'Downloads', 'impeka-landing-page' ),
				'fields' => array(
					array(
						'key'               => 'field_6924c6a1c003f',
						'label'             => \__( 'Title', 'impeka-landing-page' ),
						'name'              => 'downloads_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924c6bfc0040',
						'label'             => \__( 'Subtitle', 'impeka-landing-page' ),
						'name'              => 'downloads_subtitle',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924c6d1c0041',
						'label'             => \__( 'Lead', 'impeka-landing-page' ),
						'name'              => 'downloads_lead',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 1,
					),
					array(
						'key'               => 'field_6924c6edc0042',
						'label'             => \__( 'Downloads', 'impeka-landing-page' ),
						'name'              => 'downloads',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => \__( 'Add Row', 'impeka-landing-page' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6924c6f7c0043',
								'label'             => \__( 'Title', 'impeka-landing-page' ),
								'name'              => 'title',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6924c6edc0042',
							),
							array(
								'key'               => 'field_6924c712c0044',
								'label'             => \__( 'Download File', 'impeka-landing-page' ),
								'name'              => 'download_file',
								'aria-label'        => '',
								'type'              => 'file',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_size'          => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'parent_repeater'   => 'field_6924c6edc0042',
							),
							array(
								'key'               => 'field_6924c728c0045',
								'label'             => \__( 'Thumbnail', 'impeka-landing-page' ),
								'name'              => 'thumbnail',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => 'jpg,png',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
								'parent_repeater'   => 'field_6924c6edc0042',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'landing-page-acf-settings',
						),
					),
				),
				'menu_order'            => 20,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		\acf_add_local_field_group(
			array(
				'key'    => 'group_6924fed620121',
				'title'  => \__( 'Videos', 'impeka-landing-page' ),
				'fields' => array(
					array(
						'key'               => 'field_6924fed6ca80b',
						'label'             => \__( 'Title', 'impeka-landing-page' ),
						'name'              => 'videos_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924fef6ca80c',
						'label'             => \__( 'Videos', 'impeka-landing-page' ),
						'name'              => 'videos',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => \__( 'Add Row', 'impeka-landing-page' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6924ff0bca80d',
								'label'             => \__( 'Title', 'impeka-landing-page' ),
								'name'              => 'title',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6924fef6ca80c',
							),
							array(
								'key'               => 'field_6924ff19ca80e',
								'label'             => \__( 'Video URL', 'impeka-landing-page' ),
								'name'              => 'video_url',
								'aria-label'        => '',
								'type'              => 'url',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'allow_in_bindings' => 0,
								'placeholder'       => '',
								'parent_repeater'   => 'field_6924fef6ca80c',
							),
							array(
								'key'               => 'field_6924ff25ca80f',
								'label'             => \__( 'Thumbnail (override)', 'impeka-landing-page' ),
								'name'              => 'thumbnail',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'allow_in_bindings' => 0,
								'preview_size'      => 'medium',
								'parent_repeater'   => 'field_6924fef6ca80c',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'landing-page-acf-settings',
						),
					),
				),
				'menu_order'            => 30,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		\acf_add_local_field_group(
			array(
				'key'    => 'group_6924fd1e73121',
				'title'  => \__( 'Trusted Partners', 'impeka-landing-page' ),
				'fields' => array(
					array(
						'key'               => 'field_6924fd1ecc706',
						'label'             => \__( 'Title', 'impeka-landing-page' ),
						'name'              => 'partners_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924fd3fcc707',
						'label'             => \__( 'Content', 'impeka-landing-page' ),
						'name'              => 'partners_content',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'allow_in_bindings' => 0,
						'tabs'              => 'all',
						'toolbar'           => 'basic',
						'media_upload'      => 0,
						'delay'             => 1,
					),
					array(
						'key'               => 'field_6924fd58cc708',
						'label'             => \__( 'Image', 'impeka-landing-page' ),
						'name'              => 'partners_image',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'library'           => 'all',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'landing-page-acf-settings',
						),
					),
				),
				'menu_order'            => 40,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		\acf_add_local_field_group(
			array(
				'key'    => 'group_6924fd782bc6a',
				'title'  => \__( 'Where Chiropractors Help', 'impeka-landing-page' ),
				'fields' => array(
					array(
						'key'               => 'field_6924fd7898db9',
						'label'             => \__( 'Title', 'impeka-landing-page' ),
						'name'              => 'where_title',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924fd9998dba',
						'label'             => \__( 'Buckets', 'impeka-landing-page' ),
						'name'              => 'buckets',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => \__( 'Add Bucket', 'impeka-landing-page' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6924fdad98dbb',
								'label'             => \__( 'Title', 'impeka-landing-page' ),
								'name'              => 'title',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'allow_in_bindings' => 0,
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_6924fd9998dba',
							),
							array(
								'key'               => 'field_6924fdb498dbc',
								'label'             => \__( 'Content', 'impeka-landing-page' ),
								'name'              => 'content',
								'aria-label'        => '',
								'type'              => 'wysiwyg',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'allow_in_bindings' => 0,
								'tabs'              => 'all',
								'toolbar'           => 'basic',
								'media_upload'      => 0,
								'delay'             => 1,
								'parent_repeater'   => 'field_6924fd9998dba',
							),
						),
					),
					array(
						'key'               => 'field_6924fe96d862e',
						'label'             => \__( 'Subtitle', 'impeka-landing-page' ),
						'name'              => 'where_subtitle',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924feb4d862f',
						'label'             => \__( 'Button Link', 'impeka-landing-page' ),
						'name'              => 'where_link',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'allow_in_bindings' => 0,
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'landing-page-acf-settings',
						),
					),
				),
				'menu_order'            => 60,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

\acf_add_local_field_group(
			array(
				'key'    => 'group_6924bca9df4d9',
				'title'  => \__( 'Landing Page Footer', 'impeka-landing-page' ),
				'fields' => array(
					array(
						'key'               => 'field_6924bcaaa3642',
						'label'             => \__( 'ACC Logo (Footer)', 'impeka-landing-page' ),
						'name'              => 'acc_logo_footer',
						'aria-label'        => '',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'allow_in_bindings' => 0,
						'preview_size'      => 'medium',
					),
					array(
						'key'               => 'field_6924bd15a3643',
						'label'             => \__( 'Footer Subtitle', 'impeka-landing-page' ),
						'name'              => 'footer_subtitle',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'allow_in_bindings' => 0,
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6924bd20a3644',
						'label'             => \__( 'Footer Links', 'impeka-landing-page' ),
						'name'              => 'footer_links',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => \__( 'Add Link', 'impeka-landing-page' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6924bd2aa3645',
								'label'             => \__( 'Link', 'impeka-landing-page' ),
								'name'              => 'link',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'allow_in_bindings' => 0,
								'parent_repeater'   => 'field_6924bd20a3644',
							),
						),
					),
					array(
						'key'               => 'field_6924bd4da3646',
						'label'             => \__( 'Telephone Link', 'impeka-landing-page' ),
						'name'              => 'telephone',
						'aria-label'        => '',
						'type'              => 'link',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'allow_in_bindings' => 0,
					),
					array(
						'key'               => 'field_6924bd7ea3647',
						'label'             => \__( 'Micetype Links', 'impeka-landing-page' ),
						'name'              => 'micetype_links',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => \__( 'Add Link', 'impeka-landing-page' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6924bda0a3648',
								'label'             => \__( 'Link', 'impeka-landing-page' ),
								'name'              => 'link',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'allow_in_bindings' => 0,
								'parent_repeater'   => 'field_6924bd7ea3647',
							),
						),
					),
					array(
						'key'               => 'field_6924bdb6a3649',
						'label'             => \__( 'Socials', 'impeka-landing-page' ),
						'name'              => 'socials',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'row',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => \__( 'Add Social Link', 'impeka-landing-page' ),
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_6924bde1a364a',
								'label'             => \__( 'Link', 'impeka-landing-page' ),
								'name'              => 'link',
								'aria-label'        => '',
								'type'              => 'link',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'array',
								'allow_in_bindings' => 0,
								'parent_repeater'   => 'field_6924bdb6a3649',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'landing-page-acf-settings',
						),
					),
				),
				'menu_order'            => 100,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		
	}
}


